package core

var FlattenedPackFieldList = []string{
	"p.id as pack_fact_id",
	"pc.id as pack_config_id",
	"pc.image_url",
	"pc.item_qty as pack_item_qty",
	"pc.vendor_id as vendor_id",
	"p.created_at",
	"p.purchased_at",
	"p.opened_at",
	"p.owner_id",
	"p.active",
	"pc.description",
	"pc.title",
	"i.id as item_id",
	"i.created_at as item_created_at",
	"i.deleted_at as item_deleted_at",
	"i.updated_at as item_updated_at",
	"i.description as item_description",
	"i.vendor_id as item_vendor_id",
	"i.name as item_name",
	"i.image_url as item_image_url",
	"i.rarity_id as item_rarity_id",
	"i.content_main_url as item_content_main_url",
	"i.content_thumb_url as item_content_thumb_url",
	"i.content_type as item_content_type",
	"i.active as item_active",
	"i.notify as item_notify",
}

var PackExpandedFieldList = []string{
	"p.id as pack_config_id",
	"p.image_url as pack_image_url",
	"v.image_url as profile_image_url",
	"p.vendor_id",
	"v.active",
	"v.first_name",
	"v.last_name",
	"v.display_name",
	"v.username",
	"p.created_at",
	"p.updated_at",
	"p.deleted_at",
	"p.description",
	"p.title",
	"p.token_amount",
	"p.qty",
	"p.item_qty",
	"p.current_stock",
}

var PrivateUserFieldList = []string{
	"uid",
	"email",
	"created_at",
	"updated_at",
	"deleted_at",
	"first_name",
	"last_name",
	"display_name",
	"username",
	"birthday",
	"bio",
	"is_vendor",
	"active",
	"content_main_url",
	"content_thumb_url",
	"banner_url",
	"profile_img_version",
	"banner_img_version",
	"last_username_change_at",
}

var UserFieldList = []string{
	"uid",
	"created_at",
	"updated_at",
	"deleted_at",
	"first_name",
	"last_name",
	"display_name",
	"username",
	"birthday",
	"bio",
	"is_vendor",
	"active",
	"content_main_url",
	"content_thumb_url",
	"banner_url",
	"profile_img_version",
	"banner_img_version",
	"last_username_change_at",
}

var VendorApplicationFieldList = []string{
	"id",
	"uid",
	"username",
	"email",
	"first_name",
	"last_name",
	"birthday",
	"street_address",
	"apt_number",
	"city",
	"state",
	"zip_code",
	"submitted_at",
	"approved_at",
	"rejected_at",
	"social_link1",
	"social_link2",
	"social_link3",
	"referral_code",
	"phone_number",
}

var ReferralCodeFieldList = []string{
	"code",
	"uid",
	"active",
	"created_at",
	"removed_at",
}

var ReferralsFieldList = []string{
	"id",
	"referee_uid",
	"referrer_uid",
	"code",
	"validated_at",
}

var ReportOptFieldList = []string{
	"id",
	"opt",
	"active",
	"created_at",
	"removed_at",
}

var ReportFieldList = []string{
	"id",
	"uid",
	"reported_uid",
	"opt_id",
	"reported_at",
}
